[build]
  base = "packages/frontend"
  command = "cd ../.. && ln -sf packages/frontend/.nuxt .nuxt && cd packages/frontend && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"